services:
  - type: web_service
    name: rest-api-deploy
    env: docker
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
